---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
  namespace: qa
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports: 
    - port: 8000
      targetPort: 8000
      protocol: TCP
    