---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: rs-spc
 labels:
  app: springpetclinic
spec: 
  minReadySeconds: 10
  replicas: 2
  selector: 
   matchLabels:
     app: springpetclinic
     env: dev
  template:
   metadata:
     labels:
       env: dev
       app: spc
       version: v1.7.9
   spec:
    containers:
     - name: spcrs
       image: shaikkhajaibrahim/spcjan2024:1.0
       resources:
        requests: # Lower Limits
          memory: "128Mi"
          cpu: "100m"
       limits:
          memory: "300Mi" # Upper Limits
          cpu: "500m"
       ports: 
        - containerPort: 8080
          protocol: TCP