---
apiVersion: v1
kind: Pod
metadata: 
 name: spc
 labels:
  env: dev
  app: spc
containers:
 - name: spc-pod
   image: shaikkhajaibrahim/spcjan2024:1.0
   ports: 
    - containerPort: 8080
      protocol: TCP