---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: books-service
  annotations:
    kubernetes.io/change-cause: "version v1.0"
spec:
  serviceName: books-svc
  replicas: 1
  selector:
    matchLabels:
      app: books-svc
  template:
    metadata:
      labels:
        app: books-svc
    spec:
      containers:
        - name: books-service
          image: shaikkhajaibrahim/libbookssvc:1.0
          resources:
            requests:
              memory: 24M
              cpu: 100m
            limits:
              memory: 128M
              cpu: 500m
          envFrom:
            - secretRef:
                name: books-svc-secrets
          ports:
          - containerPort: 8000
          volumeMounts:
            - name: books-storage-vol
              mountPath: /var/lib/postgresql/data
              subPath: data
      volumeClaimTemplates:
        - metadata:
            name: users-storage-vol
          spec:
            accessModes: 
              - ReadWriteOnce
            storageClassName: managed  
            resources:
              requests:
                storage: 1Gi        

---
apiVersion: v1
kind: Service
metadata:
  name: books-svc
spec:
  type: ClusterIP
  selector:
    app: books-svc
  ports:
  - port: 8000
    targetPort: 8000