---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: booksdb
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels: 
      app: booksdb
  serviceName: booksdb-svc
  template:
    metadata:
      labels: 
        app: booksdb
    spec:
      automountServiceAccountToken: "false"
      containers:
        - name: booksdb
          image: postgres:15-alpine
          envFrom:
            - secretRef: 
                name: books-svc-secrets
          resources:
            requests:
             memory: 64M
             cpu: 100m
            limits:
             memory: 256M
             cpu: 500m
          ports:
           - containerPort: 5432
          volumeMounts:
           - name: books-db-vol
             mountPath: /var/lib/postgresql/data
             subPath: data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: books-db-vol
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata: 
  name: booksdb-svc
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: booksdb
  ports:
    - port: 5432
      targetPort: 5432            