---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: usersdb
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels: 
      app: usersdb
  serviceName: usersdb-svc
  template:
    metadata:
      labels: 
        app: usersdb
    spec:
      containers:
        - name: usersdb
          image: postgres:15-alpine
          envFrom:
            - secretRef: 
                name: users-svc-secrets
          resources:
            requests:
             memory: 64M
             cpu: 100m
            limits:
             memory: 256M
             cpu: 500m
          ports:
           - containerPort: 5432
          volumeMounts:
           - name: users-db-vol
             mountPath: /var/lib/postgresql/data
             subPath: data
  volumeClaimTemplates:
        - metadata:
            name: users-db-vol
          spec:
           accessModes:
            - ReadWriteOnce
           storageClassName: managed
           resources:
             requests:
               storage: 1Gi    
    

#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: users-db-vol
#spec:
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: managed
#  resources:
#    requests:
#      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata: 
  name: usersdb-svc
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: usersdb
  ports:
    - port: 5432
      targetPort: 5432            