---
apiVersion: apps/v1
kind: Deployment
metadata: 
 name: users-svc-rs
 annotations:
    kubernetes.io/change-cause: "version v1.0"
spec:
 minReadySeconds: 10
 replicas: 1
 selector:
  matchLabels: 
   app: users-svc
 template:
  metadata:
   labels: 
    app: users-svc
  spec:
   containers: 
    - name: users-service
      image: shaikkhajaibrahim/libbookssvc:1.0
       #envFrom:
       # - configMapRef: 
       #    name: users-svc-config
      envFrom: 
        - secretRef: 
            name: users-svc-secrets
      resources:
        requests:
         memory: 24M
         cpu: 100m
        limits:
         memory: 128M
         cpu: 500m
      ports:
        - containerPort: 8000

---
apiVersion: v1 
kind: Service
metadata:
 name: users-svc
spec:
 type: ClusterIP
 selector:  
  app: users-svc
 ports:
  - port: 8000
    targetPort: 8000