---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: books-sts
spec:
  minReadySeconds: 5
  replicas: 1
  selector: 
    matchLabels: 
      app: books-db
  serviceName: books-svc
  template: 
    metadata:
      labels:
        app: books-db
        name: booksdb
    spec:
      containers:
        - name: books-db
          image: postgres:15-alpine
          envFrom:
            - secretRef:
                name: books-secrets
                optional: True
          resources:
            requests:
              memory: "50Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: booksdb-vol
              mountPath: /var/lib/postgresql/data
              subPath: data
  volumeClaimTemplates:
  - metadata: 
      name: booksdb-vol
    spec: 
      accessModes: 
        - ReadWriteOnce
      storageClassName: managed
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: booksdb-service
spec:
  type: ClusterIP
  clusterIP: None
  selector: 
    name: books-db
  ports:
    - port: 5432
      targetPort: 5432