---
apiVersion: v1 
kind: Pod
metadata: 
  name: mysql
  labels: 
    name: mysql
spec: 
  containers: 
    - name: mysql
      image: mysql:9
      resources: 
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "1000m"
      envFrom:
        - configMapRef:
            name: mysql  
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: librarydb
          mountPath: /var/lib/mysql
  volumes: 
    - name: librarydb
      persistentVolumeClaim: 
        claimName: mysql-pvc