---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
 name: books-svc-rs
spec:
 minReadySeconds: 10
 replicas: 1
 selector:
  matchLabels: 
   app: books-svc
 template:
  metadata:
   labels: 
    app: books-svc
  spec:
   containers: 
    - name: books-serice
      image: shaikkhajaibrahim/libbookssvc:1.0
      #env:
      #- name: DATABASE_URL
      # value: "postgresql://user:password@books-db:5432/booksdb"
      #- name: SECRET_KEY
      # value: "YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k"
      envFrom:
        - configMapRef:
          name: books-svc-config
      resources:
        requests:
         memory: 24M
         cpu: 100m
        limits:
         memory: 128M
         cpu: 500m
      ports:
        - containerPort: 8000

---
apiVersion: v1 
kind: Service
metadata:
 name: books-svc
spec:
 type: ClusterIP
 selector:  
  app: books-svc
 ports:
  - port: 8000
    targetPort: 8000