---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: users-db-config
data: 
    POSTGRES_USER: users
    POSTGRES_PASSWORD: password
    POSTGRES_DB: usersdb
---
apiVersion: v1 
kind: ConfigMap
metadata: 
  name: books-db-config
data: 
    POSTGRES_USER: books
    POSTGRES_PASSWORD: password
    POSTGRES_DB: booksdb
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: users-svc-config
data: 
  DATABASE_URL: "postgresql://users:password@users-db:5432/usersdb"
  SECRET_KEY: "YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k"
---
apiVersion: v1 
kind: ConfigMap
metadata:
  name: books-svc-config
data: 
  DATABASE_URL: "postgresql://user:password@books-db:5432/booksdb"
  SECRET_KEY: "YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k"
   

