---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
 name: users-svc-rs
spec:
 minReadySeconds: 10
 replicas: 1
 selector:
  matchLabels: 
   app: users-svc
 template:
  metadata:
   labels: 
    app: users-svc
  spec:
   containers: 
    - name: users-serice
      image: shaikkhajaibrahim/libbookssvc:1.0
      env:
       - name: DATABASE_URL
         value: "postgresql://users:password@users-db:5432/usersdb"
       - name: SECRET_KEY
         value: "YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k"
      resources:
        requests:
         memory: 24M
         cpu: 100m
        limits:
         memory: 128M
         cpu: 500m
      ports:
        - containerPort: 8000

---
apiVersion: v1 
kind: Service
metadata:
 name: users-svc
spec:
 type: ClusterIP
 selector:  
  db: users-svc
 ports:
  - port: 8000
    targetPort: 8000
  

    