---
apiVersion: v1
kind: pod 
metadata: 
  name: app
spec: 
  containers:
    - name: webimage
      image: nginx:1.27
      args: 
       - sleep
       - 1d
      env:
       - name: USERNAME
         value: ZeeshanAhmed
       - name: PASSWORD
         value: zeeshan799351